/* dsda-options.h - generated by gen-declaration.py: the settings the core
 * declares, by name, and each enum setting's options as waterbox.config has
 * them - what a project's settings say. Included by lmp-import.cpp. */
#ifndef DSDA_OPTIONS_H
#define DSDA_OPTIONS_H

static const char *const k_setting_names[] = {
	"game",
	"version",
	"compatibilityLevel",
	"skillLevel",
	"multiplayerMode",
	"initialEpisode",
	"initialMap",
	"fastMonsters",
	"monstersRespawn",
	"noMonsters",
	"pistolStart",
	"coopSpawns",
	"chainEpisodes",
	"alwaysRun",
	"renderWipescreen",
	"turningResolution",
	"mouseTurnSensitivity",
	"mouseRunSensitivity",
	"strafe50Turns",
	"preventLevelExit",
	"preventGameEnd",
	"turbo",
	"rngSeed",
	"player1Present",
	"player2Present",
	"player3Present",
	"player4Present",
	"player1Class",
	"player2Class",
	"player3Class",
	"player4Class",
	"scaleFactor",
	"internalAspect",
	"sfxVolume",
	"musicVolume",
	"gamma",
	"showMessages",
	"reportSecrets",
	"hudMode",
	"dsdaExHud",
	"displayCoordinates",
	"displayCommands",
	"mapTotals",
	"mapTime",
	"mapCoordinates",
	"mapOverlay",
	"mapDetails",
	"mapTrail",
	"mapTrailSize",
	"fullVision",
	"displayPlayer",
	"soloNet",
	"demoOptions",
	"extendedCommands",
	"emulatePrBoom",
	"spechitAddress",
	"overrunSpechit",
	"overrunReject",
	"overrunIntercept",
	"overrunPlayeringame",
	"overrunDonut",
	"overrunMissedBackside",
	nullptr
};

static const char *const k_options_compatibilityLevel[] = { "0 - Doom v1.2", "1 - Doom v1.666", "2 - Doom & Doom 2 v1.9", "3 - Ultimate Doom & Doom95", "4 - Final Doom", "5 - DOSDoom", "6 - TASDoom", "7 - Boom's Vanilla Compatibility Mode", "8 - Boom v2.01", "9 - Boom v2.02", "10 - LxDoom", "11 - MBF", "12 - PrBoom v2.03beta", "13 - PrBoom v2.1.0", "14 - PrBoom v2.1.1 - 2.2.6", "15 - PrBoom v2.3.x", "16 - PrBoom v2.4.0", "17 - PrBoom Latest", "21 - MBF21", nullptr };
static const char *const k_options_skillLevel[] = { "1 - I'm too young to die", "2 - Hey, not too rough", "3 - Hurt me plenty", "4 - Ultra-Violence", "5 - Nightmare!", nullptr };
static const char *const k_options_multiplayerMode[] = { "Single Player / Cooperative", "Deathmatch", "Alternate Deathmatch (v2.0)", nullptr };
static const char *const k_options_turningResolution[] = { "16 bits (longtics)", "8 bits (shorttics)", nullptr };
static const char *const k_options_strafe50Turns[] = { "Ignore", "Allow", nullptr };
static const char *const k_options_playerClass[] = { "Fighter", "Cleric", "Mage", nullptr };
static const char *const k_options_internalAspect[] = { "Native", "16:9", "16:10", "4:3", nullptr };
static const char *const k_options_hudMode[] = { "Vanilla", "DSDA", "None", nullptr };
static const char *const k_options_mapOverlay[] = { "Disabled", "Enabled", "Dark", nullptr };
static const char *const k_options_mapDetails[] = { "Normal", "Linedefs", "Linedefs and things", nullptr };
static const char *const k_options_extendedCommands[] = { "Off", "On", "On, with casual features", nullptr };

#endif
