/* dsda-versions.h - generated by gen-declaration.py: the IWAD releases the core
 * knows (the version setting's values), each with its game (the machine), the
 * name its IWAD is mounted under (its firmware id: upstream tells the game and
 * its mission by it), its controller, and whether its maps come in episodes
 * (-warp takes an episode then). The first is the default. */
#ifndef DSDA_VERSIONS_H
#define DSDA_VERSIONS_H

#include "dsda-input.h"

struct dsda_version
{
	const char *id;
	const char *game;
	const char *iwad;
	int format;
	int episodic;
};

static const struct dsda_version k_versions[] = {
	{ "doom2-1.9", "doom2", "doom2.wad", FORMAT_DOOM, 0 },
	{ "doom-ultimate", "doom", "doom.wad", FORMAT_DOOM, 1 },
	{ "tnt", "tnt", "tnt.wad", FORMAT_DOOM, 0 },
	{ "plutonia", "plutonia", "plutonia.wad", FORMAT_DOOM, 0 },
	{ "heretic-1.2", "heretic", "heretic.wad", FORMAT_HERETIC, 1 },
	{ "hexen-1.1", "hexen", "hexen.wad", FORMAT_HEXEN, 0 },
	{ "chex", "chex", "chex.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.13.0", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.12.1", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.12.0", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.11.3", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.11.2", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.11.1", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom1-0.11", "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom2-0.13.0", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.12.1", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.12.0", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.11.3", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.11.2", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.11.1", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
	{ "freedoom2-0.11", "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
};

#endif
