/* dsda-games.h - generated by gen-declaration.py: the games the core plays (the game
 * setting's values: the machines), each with the name its IWAD is mounted under (its
 * firmware id: upstream tells the game and its mission by it), its controller, and
 * whether its maps come in episodes (-warp takes an episode then); then the IWAD dumps
 * the core has been tested with, by SHA1 - for telling a demo's game, not a setting.
 * The first game is the default. */
#ifndef DSDA_GAMES_H
#define DSDA_GAMES_H

#include "dsda-input.h"

struct dsda_game
{
	const char *id;
	const char *iwad;
	int format;
	int episodic;
};

static const struct dsda_game k_games[] = {
	{ "doom2", "doom2.wad", FORMAT_DOOM, 0 },
	{ "doom", "doom.wad", FORMAT_DOOM, 1 },
	{ "tnt", "tnt.wad", FORMAT_DOOM, 0 },
	{ "plutonia", "plutonia.wad", FORMAT_DOOM, 0 },
	{ "heretic", "heretic.wad", FORMAT_HERETIC, 1 },
	{ "hexen", "hexen.wad", FORMAT_HEXEN, 0 },
	{ "chex", "chex.wad", FORMAT_DOOM, 1 },
	{ "freedoom1", "freedoom1.wad", FORMAT_DOOM, 1 },
	{ "freedoom2", "freedoom2.wad", FORMAT_DOOM, 0 },
};

struct dsda_known_iwad
{
	const char *game;
	const char *label;
	const char *sha1;
};

static const struct dsda_known_iwad k_known_iwads[] = {
	{ "doom2", "Doom II v1.9", "7EC7652FCFCE8DDC6E801839291F0E28EF1D5AE7" },
	{ "doom", "The Ultimate Doom v1.9", "117015379C529573510BE08CF59810AA10BB934E" },
	{ "tnt", "TNT: Evilution (original release)", "139E26D801A64B404B8D898DEFCA10227A61867B" },
	{ "plutonia", "The Plutonia Experiment (original release)", "327F8C41EBD4138354E9FCA63CEBBBD1B9489749" },
	{ "heretic", "Heretic v1.2 (three episodes)", "A54C5D30629976A649119C5CE8BABAE2DDFB1A60" },
	{ "hexen", "Hexen v1.1", "4B53832F0733C1E29E5F1DE2428E5475E891AF29" },
	{ "chex", "Chex Quest", "ECA9CFF1014CE5081804E193588D96C6DDB35432" },
	{ "freedoom1", "Freedoom: Phase 1 v0.13.0", "97BB88094A51457A8DCAD98C58BE22A2D0FA9A37" },
	{ "freedoom1", "Freedoom: Phase 1 v0.12.1", "E9BF428B73A04423EA7A0E9F4408F71DF85AB175" },
	{ "freedoom1", "Freedoom: Phase 1 v0.12.0", "351A207B5FE520EA618BC8659D176F4C39047D20" },
	{ "freedoom1", "Freedoom: Phase 1 v0.11.3", "36DB0EB476486FA56C43F24D9B23E9D8AFDBBFF5" },
	{ "freedoom1", "Freedoom: Phase 1 v0.11.2", "7931A41E6B1C6B7C701AB16D7355E7685F96B1CC" },
	{ "freedoom1", "Freedoom: Phase 1 v0.11.1", "F81E8BB84000DAECD682ABF95357CF55FB57FBB7" },
	{ "freedoom1", "Freedoom: Phase 1 v0.11", "9E38DCC0D1E9FBD20382BA19A6BDF11F7A2B0502" },
	{ "freedoom2", "Freedoom: Phase 2 v0.13.0", "975F781E6D801C0A23E3CAA33F70493EFE68A880" },
	{ "freedoom2", "Freedoom: Phase 2 v0.12.1", "51C997F430DC12ABBA7888C2D83C237A8E0758A7" },
	{ "freedoom2", "Freedoom: Phase 2 v0.12.0", "18C6EF3F269A80FEED16EB46C7577D29D4209098" },
	{ "freedoom2", "Freedoom: Phase 2 v0.11.3", "0C03D1F754B98C53F292F66BC9505A29F47C6A9F" },
	{ "freedoom2", "Freedoom: Phase 2 v0.11.2", "26FBA39016C26CF58756AA2CBF715A34F83857D3" },
	{ "freedoom2", "Freedoom: Phase 2 v0.11.1", "8B4385450D3C622CA7AAE3D00C7E15829DA264CF" },
	{ "freedoom2", "Freedoom: Phase 2 v0.11", "25110745824A107F80B078CF368A1045661DF3B5" },
};

#endif
